In [4]:
#import neseccary libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from torchvision.utils import save_image
import torch
import torchvision
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

In [2]:
#import data
data_train = pd.read_excel("Data/data_train.xls")
data_test = pd.read_excel("Data/data_test.xls").drop(columns = ['ДЕФОЛТ60 (Прогноз)', 'Скоринговый балл'])
data_test['ДЕФОЛТ60'] = 0
data_train['train'] = 1
data_test['train'] = 0
#print(data_train.info())
#print(data_test.info())

#exploratory analisys
#profile = ProfileReport(data_train, title = "Data Stats")
#profile.to_file("DataReport.html")

#fig = px.histogram(x = data_train['ОТДЕЛЕНИЕ'])
#fig.show()

#correct one row
data_train.loc[data_train['СУММА_ВЫДАННОГО_КРЕДИТА'] == max(data_train['СУММА_ВЫДАННОГО_КРЕДИТА']),\
               'СУММА_ВЫДАННОГО_КРЕДИТА'] = 70000

#data_test.head()
data = pd.concat([data_train, data_test], axis = 0)
print(data.info())

del data_train
del data_test

data.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9048 entries, 0 to 3037
Data columns (total 29 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ИД                           9048 non-null   int64
 1   ВОЗРАСТ                      9048 non-null   float64
 2   ВОЗРАСТ.ЛЕТ                  9048 non-null   int64
 3   ПОЛ                          9048 non-null   int64
 4   СМЕНА_МЖ                     9048 non-null   int64
 5   ЗАГРАН                       9048 non-null   int64
 6   БРАК                         9048 non-null   int64
 7   ДЕТИ                         9048 non-null   int64
 8   ИЖДИВЕНЦЫ                    9048 non-null   int64
 9   ОБРАЗОВАНИЕ                  9048 non-null   int64
 10  ИНОСТР.ЯЗЫК                  9048 non-null   int64
 11  АВТО                         9048 non-null   int64
 12  ОТРАСЛЬ                      9048 non-null   int64
 13  РАБОТА_ПО_НАПР               9048 non-null   int64
 14  РАБОТА_В_ОРГ                 9048 non-null   int64
 15  ДОЛЖНОСТЬ                    9048 non-null   int64
 16  ДОХОД_СЕМЬИ_                 9048 non-null   int64
 17  ДОХОД_НА_ОДНОГО_ЧЛЕНА_СЕМЬИ  9048 non-null   float64
 18  ПЕРСОНАЛЬНЫЙ_ДОХОД           9048 non-null   int64
 19  СУММА_ВЫДАННОГО_КРЕДИТА      9048 non-null   float64
 20  ОТДЕЛЕНИЕ                    9048 non-null   int64
 21  ГОРОД                        9048 non-null   int64
 22  ЗАПРОШЕННАЯ_СУММА            9048 non-null   int64
 23  СОБСТВЕННИК_ФАКТ.            9048 non-null   int64
 24  ДОХОД_СУПРУГИ(А)             9048 non-null   int64
 25  КРЕДИТЫ_ПОГАШЕНЫ             9048 non-null   int64
 26  ПЕРВЫЙ_КРЕДИТ                9048 non-null   int64
 27  ДЕФОЛТ60                     9048 non-null   int64
 28  train                        9048 non-null   int64
dtypes: float64(3), int64(26)
memory usage: 2.1 MB
None

,ИД,ВОЗРАСТ,ВОЗРАСТ.ЛЕТ,ПОЛ,СМЕНА_МЖ,ЗАГРАН,БРАК,ДЕТИ,ИЖДИВЕНЦЫ,ОБРАЗОВАНИЕ,...,СУММА_ВЫДАННОГО_КРЕДИТА,ОТДЕЛЕНИЕ,ГОРОД,ЗАПРОШЕННАЯ_СУММА,СОБСТВЕННИК_ФАКТ.,ДОХОД_СУПРУГИ(А),КРЕДИТЫ_ПОГАШЕНЫ,ПЕРВЫЙ_КРЕДИТ,ДЕФОЛТ60,train
0,1,26.936986,27,1,0,0,2,0,0,2,...,60000.0,27,10,60000,5,0,0,0,0,1
1,3,31.742466,32,2,0,0,1,2,2,2,...,50000.0,29,12,50000,4,12000,0,1,0,1
2,4,23.172603,23,1,0,0,1,1,1,2,...,30000.0,39,1,30000,3,0,1,0,1,1
3,5,24.424658,24,1,0,0,2,0,0,2,...,70000.0,115,1,70000,3,0,0,0,1,1
4,6,28.654795,29,2,0,0,2,0,0,2,...,15000.0,53,9,15000,1,0,0,0,0,1

In [3]:
#data preprocessing

#remove some columns
drop_columns = ['ВОЗРАСТ.ЛЕТ', 'ЗАГРАН', 'ЗАПРОШЕННАЯ_СУММА', 'ИД']
data_processed = data.drop(columns = drop_columns)

#re-encode some variables
data_processed['ПОЛ'] -= 1

#one-hot encoding
ohe_columns = ['АВТО', 'БРАК', 'ГОРОД', 'ДОЛЖНОСТЬ', 'ИНОСТР.ЯЗЫК', 'ОБРАЗОВАНИЕ', 'ОТДЕЛЕНИЕ', 'ОТРАСЛЬ',\
               'РАБОТА_В_ОРГ', 'РАБОТА_ПО_НАПР', 'СМЕНА_МЖ']
for col in ohe_columns:
    data_processed = pd.concat([data_processed, pd.get_dummies(data_processed[col], prefix = col)], axis = 1)
data_processed = data_processed.drop(columns = ohe_columns)

#make 256-dimensional feature vectors to later create 16*16 grayscale images
print("Total number of features:", len(list(data_processed.columns)) - 2)
drop_columns_extra = ['ГОРОД_4', 'ГОРОД_7', 'ГОРОД_11', 'ГОРОД_14', 'ГОРОД_17', 'ГОРОД_18',\
                      'ГОРОД_21', 'ГОРОД_23', 'ГОРОД_24', 'ОТДЕЛЕНИЕ_96', 'ОТДЕЛЕНИЕ_98', 'ОТДЕЛЕНИЕ_257']
data_processed = data_processed.drop(columns = drop_columns_extra)
print("Final number of features:", len(list(data_processed.columns)) - 2)
columns_order = ['АВТО_0', 'АВТО_1', 'АВТО_2', 'АВТО_3', 'БРАК_1', 'БРАК_2', 'БРАК_3', 'БРАК_4', 'ГОРОД_1',\
                 'ГОРОД_2', 'ГОРОД_3', 'ГОРОД_5',\
                 'ГОРОД_6', 'ГОРОД_8', 'ГОРОД_9', 'ГОРОД_10', 'ГОРОД_12', 'ГОРОД_13', 'ГОРОД_15', 'ГОРОД_16',\
                 'ГОРОД_19', 'ГОРОД_20', 'ГОРОД_22', 'ГОРОД_27', 'ГОРОД_29', 'ГОРОД_30', 'ГОРОД_31', 'ГОРОД_32',\
                 'ГОРОД_33', 'ГОРОД_35', 'ДОЛЖНОСТЬ_1', 'ДОЛЖНОСТЬ_3', 'ДОЛЖНОСТЬ_4', 'ДОЛЖНОСТЬ_5',\
                 'ДОЛЖНОСТЬ_6', 'ИНОСТР.ЯЗЫК_0', 'ИНОСТР.ЯЗЫК_1', 'ИНОСТР.ЯЗЫК_2', 'ИНОСТР.ЯЗЫК_3',\
                 'ИНОСТР.ЯЗЫК_4', 'ОБРАЗОВАНИЕ_1', 'ОБРАЗОВАНИЕ_2', 'ОБРАЗОВАНИЕ_3', 'ОБРАЗОВАНИЕ_4',\
                 'ОТДЕЛЕНИЕ_3', 'ОТДЕЛЕНИЕ_7', 'ОТДЕЛЕНИЕ_8', 'ОТДЕЛЕНИЕ_10', 'ОТДЕЛЕНИЕ_11', 'ОТДЕЛЕНИЕ_14',\
                 'ОТДЕЛЕНИЕ_16', 'ОТДЕЛЕНИЕ_17', 'ОТДЕЛЕНИЕ_18', 'ОТДЕЛЕНИЕ_24', 'ОТДЕЛЕНИЕ_25', 'ОТДЕЛЕНИЕ_27',\
                 'ОТДЕЛЕНИЕ_28', 'ОТДЕЛЕНИЕ_29', 'ОТДЕЛЕНИЕ_30', 'ОТДЕЛЕНИЕ_31', 'ОТДЕЛЕНИЕ_33', 'ОТДЕЛЕНИЕ_36',\
                 'ОТДЕЛЕНИЕ_37', 'ОТДЕЛЕНИЕ_38', 'ОТДЕЛЕНИЕ_39', 'ОТДЕЛЕНИЕ_41', 'ОТДЕЛЕНИЕ_50', 'ОТДЕЛЕНИЕ_51',\
                 'ОТДЕЛЕНИЕ_52', 'ОТДЕЛЕНИЕ_53', 'ОТДЕЛЕНИЕ_54', 'ОТДЕЛЕНИЕ_55', 'ОТДЕЛЕНИЕ_56', 'ОТДЕЛЕНИЕ_57',\
                 'ОТДЕЛЕНИЕ_58', 'ОТДЕЛЕНИЕ_59', 'ОТДЕЛЕНИЕ_60', 'ОТДЕЛЕНИЕ_64', 'ОТДЕЛЕНИЕ_65', 'ОТДЕЛЕНИЕ_66',\
                 'ОТДЕЛЕНИЕ_70', 'ОТДЕЛЕНИЕ_73', 'ОТДЕЛЕНИЕ_78', 'ОТДЕЛЕНИЕ_79', 'ОТДЕЛЕНИЕ_80', 'ОТДЕЛЕНИЕ_83',\
                 'ОТДЕЛЕНИЕ_84', 'ОТДЕЛЕНИЕ_85', 'ОТДЕЛЕНИЕ_90', 'ОТДЕЛЕНИЕ_103', 'ОТДЕЛЕНИЕ_104',\
                 'ОТРАСЛЬ_1', 'ОТРАСЛЬ_2',\
                 'ОТРАСЛЬ_3', 'ОТРАСЛЬ_4', 'ОТРАСЛЬ_5', 'ОТРАСЛЬ_6', 'ОТРАСЛЬ_7', 'ОТРАСЛЬ_8', 'ОТРАСЛЬ_9',\
                 'ОТРАСЛЬ_10', 'ОТРАСЛЬ_11', 'ОТРАСЛЬ_12', 'ОТРАСЛЬ_13', 'ОТРАСЛЬ_14', 'ОТРАСЛЬ_15',\
                 'ОТРАСЛЬ_16', 'ОТРАСЛЬ_17', 'ОТРАСЛЬ_18', 'ОТРАСЛЬ_19', 'ОТРАСЛЬ_20', 'ОТРАСЛЬ_21',\
                 'ОТРАСЛЬ_22', 'ОТРАСЛЬ_23', 'ОТРАСЛЬ_24', 'ОТРАСЛЬ_25', 'ОТРАСЛЬ_26', 'ОТРАСЛЬ_27',\
                 'ОТРАСЛЬ_28', 'ОТРАСЛЬ_29', 'ОТРАСЛЬ_30', 'ОТРАСЛЬ_31', 'ОТРАСЛЬ_32', 'ОТРАСЛЬ_33',\
                 'ОТРАСЛЬ_34', 'ОТРАСЛЬ_35', 'ОТРАСЛЬ_36', 'ОТРАСЛЬ_37', 'ОТРАСЛЬ_38', 'ОТРАСЛЬ_39',\
                 'ОТРАСЛЬ_40', 'ОТРАСЛЬ_41', 'ОТРАСЛЬ_42',\
                 'ВОЗРАСТ', 'ПОЛ', 'ДЕТИ', 'ИЖДИВЕНЦЫ', 'ДОХОД_СЕМЬИ_', 'ДОХОД_НА_ОДНОГО_ЧЛЕНА_СЕМЬИ',\
                 'ПЕРСОНАЛЬНЫЙ_ДОХОД', 'СУММА_ВЫДАННОГО_КРЕДИТА', 'СОБСТВЕННИК_ФАКТ.', 'ДОХОД_СУПРУГИ(А)',\
                 'КРЕДИТЫ_ПОГАШЕНЫ', 'ПЕРВЫЙ_КРЕДИТ', 'ДЕФОЛТ60', 'train',\
                 'ОТДЕЛЕНИЕ_107', 'ОТДЕЛЕНИЕ_108', 'ОТДЕЛЕНИЕ_110', 'ОТДЕЛЕНИЕ_114', 'ОТДЕЛЕНИЕ_115',\
                 'ОТДЕЛЕНИЕ_116', 'ОТДЕЛЕНИЕ_117', 'ОТДЕЛЕНИЕ_119', 'ОТДЕЛЕНИЕ_120', 'ОТДЕЛЕНИЕ_121',\
                 'ОТДЕЛЕНИЕ_122', 'ОТДЕЛЕНИЕ_125', 'ОТДЕЛЕНИЕ_126', 'ОТДЕЛЕНИЕ_127', 'ОТДЕЛЕНИЕ_135',\
                 'ОТДЕЛЕНИЕ_136', 'ОТДЕЛЕНИЕ_137', 'ОТДЕЛЕНИЕ_138', 'ОТДЕЛЕНИЕ_140', 'ОТДЕЛЕНИЕ_143',\
                 'ОТДЕЛЕНИЕ_144', 'ОТДЕЛЕНИЕ_145', 'ОТДЕЛЕНИЕ_146', 'ОТДЕЛЕНИЕ_148', 'ОТДЕЛЕНИЕ_149',\
                 'ОТДЕЛЕНИЕ_153', 'ОТДЕЛЕНИЕ_154', 'ОТДЕЛЕНИЕ_155', 'ОТДЕЛЕНИЕ_156', 'ОТДЕЛЕНИЕ_157',\
                 'ОТДЕЛЕНИЕ_159', 'ОТДЕЛЕНИЕ_160', 'ОТДЕЛЕНИЕ_161', 'ОТДЕЛЕНИЕ_162', 'ОТДЕЛЕНИЕ_163',\
                 'ОТДЕЛЕНИЕ_164', 'ОТДЕЛЕНИЕ_165', 'ОТДЕЛЕНИЕ_166', 'ОТДЕЛЕНИЕ_167', 'ОТДЕЛЕНИЕ_168',\
                 'ОТДЕЛЕНИЕ_169', 'ОТДЕЛЕНИЕ_170', 'ОТДЕЛЕНИЕ_171', 'ОТДЕЛЕНИЕ_177', 'ОТДЕЛЕНИЕ_178',\
                 'ОТДЕЛЕНИЕ_179', 'ОТДЕЛЕНИЕ_181', 'ОТДЕЛЕНИЕ_182', 'ОТДЕЛЕНИЕ_184', 'ОТДЕЛЕНИЕ_185',\
                 'ОТДЕЛЕНИЕ_186', 'ОТДЕЛЕНИЕ_187', 'ОТДЕЛЕНИЕ_188', 'ОТДЕЛЕНИЕ_189', 'ОТДЕЛЕНИЕ_190',\
                 'ОТДЕЛЕНИЕ_191', 'ОТДЕЛЕНИЕ_192', 'ОТДЕЛЕНИЕ_193', 'ОТДЕЛЕНИЕ_194', 'ОТДЕЛЕНИЕ_195',\
                 'ОТДЕЛЕНИЕ_196', 'ОТДЕЛЕНИЕ_199', 'ОТДЕЛЕНИЕ_200', 'ОТДЕЛЕНИЕ_201', 'ОТДЕЛЕНИЕ_202',\
                 'ОТДЕЛЕНИЕ_203', 'ОТДЕЛЕНИЕ_204', 'ОТДЕЛЕНИЕ_205', 'ОТДЕЛЕНИЕ_206', 'ОТДЕЛЕНИЕ_208',\
                 'ОТДЕЛЕНИЕ_210', 'ОТДЕЛЕНИЕ_211', 'ОТДЕЛЕНИЕ_212', 'ОТДЕЛЕНИЕ_213', 'ОТДЕЛЕНИЕ_214',\
                 'ОТДЕЛЕНИЕ_216', 'ОТДЕЛЕНИЕ_217', 'ОТДЕЛЕНИЕ_218', 'ОТДЕЛЕНИЕ_219', 'ОТДЕЛЕНИЕ_220',\
                 'ОТДЕЛЕНИЕ_223', 'ОТДЕЛЕНИЕ_224', 'ОТДЕЛЕНИЕ_225', 'ОТДЕЛЕНИЕ_226', 'ОТДЕЛЕНИЕ_227',\
                 'ОТДЕЛЕНИЕ_228', 'ОТДЕЛЕНИЕ_229', 'ОТДЕЛЕНИЕ_230', 'ОТДЕЛЕНИЕ_231', 'ОТДЕЛЕНИЕ_232',\
                 'ОТДЕЛЕНИЕ_240', 'ОТДЕЛЕНИЕ_241', 'ОТДЕЛЕНИЕ_243', 'ОТДЕЛЕНИЕ_245', 'ОТДЕЛЕНИЕ_246',\
                 'ОТДЕЛЕНИЕ_247', 'ОТДЕЛЕНИЕ_248', 'ОТДЕЛЕНИЕ_249', 'ОТДЕЛЕНИЕ_264',\
                 'РАБОТА_В_ОРГ_1', 'РАБОТА_В_ОРГ_2', 'РАБОТА_В_ОРГ_3',\
                 'РАБОТА_ПО_НАПР_0', 'РАБОТА_ПО_НАПР_1', 'РАБОТА_ПО_НАПР_2', 'РАБОТА_ПО_НАПР_3', 'СМЕНА_МЖ_0',\
                 'СМЕНА_МЖ_1', 'СМЕНА_МЖ_2', 'СМЕНА_МЖ_3', 'СМЕНА_МЖ_4']
data_processed = data_processed[columns_order]
print(list(data_processed.columns))

#min max scaler
data_train = data_processed[data_processed['train'] == 1]
data_test = data_processed[data_processed['train'] == 0]
del data_processed
numerical_features = ['ВОЗРАСТ', 'ДЕТИ', 'ДОХОД_НА_ОДНОГО_ЧЛЕНА_СЕМЬИ', 'ДОХОД_СЕМЬИ_', 'ДОХОД_СУПРУГИ(А)',\
                      'СУММА_ВЫДАННОГО_КРЕДИТА', 'ИЖДИВЕНЦЫ', 'ПЕРСОНАЛЬНЫЙ_ДОХОД', 'СОБСТВЕННИК_ФАКТ.']
for feature in numerical_features:
    feature_min = data_train[feature].min()
    feature_max = data_train[feature].max()
    data_train[feature] = (data_train[feature] - feature_min)/(feature_max - feature_min)
    data_test[feature] = ((data_test[feature] - feature_min)/(feature_max - feature_min)).clip(0, 1)

Total number of features: 268
Final number of features: 256
['АВТО_0', 'АВТО_1', 'АВТО_2', 'АВТО_3', 'БРАК_1', 'БРАК_2', 'БРАК_3', 'БРАК_4', 'ГОРОД_1', 'ГОРОД_2', 'ГОРОД_3', 'ГОРОД_5', 'ГОРОД_6', 'ГОРОД_8', 'ГОРОД_9', 'ГОРОД_10', 'ГОРОД_12', 'ГОРОД_13', 'ГОРОД_15', 'ГОРОД_16', 'ГОРОД_19', 'ГОРОД_20', 'ГОРОД_22', 'ГОРОД_27', 'ГОРОД_29', 'ГОРОД_30', 'ГОРОД_31', 'ГОРОД_32', 'ГОРОД_33', 'ГОРОД_35', 'ДОЛЖНОСТЬ_1', 'ДОЛЖНОСТЬ_3', 'ДОЛЖНОСТЬ_4', 'ДОЛЖНОСТЬ_5', 'ДОЛЖНОСТЬ_6', 'ИНОСТР.ЯЗЫК_0', 'ИНОСТР.ЯЗЫК_1', 'ИНОСТР.ЯЗЫК_2', 'ИНОСТР.ЯЗЫК_3', 'ИНОСТР.ЯЗЫК_4', 'ОБРАЗОВАНИЕ_1', 'ОБРАЗОВАНИЕ_2', 'ОБРАЗОВАНИЕ_3', 'ОБРАЗОВАНИЕ_4', 'ОТДЕЛЕНИЕ_3', 'ОТДЕЛЕНИЕ_7', 'ОТДЕЛЕНИЕ_8', 'ОТДЕЛЕНИЕ_10', 'ОТДЕЛЕНИЕ_11', 'ОТДЕЛЕНИЕ_14', 'ОТДЕЛЕНИЕ_16', 'ОТДЕЛЕНИЕ_17', 'ОТДЕЛЕНИЕ_18', 'ОТДЕЛЕНИЕ_24', 'ОТДЕЛЕНИЕ_25', 'ОТДЕЛЕНИЕ_27', 'ОТДЕЛЕНИЕ_28', 'ОТДЕЛЕНИЕ_29', 'ОТДЕЛЕНИЕ_30', 'ОТДЕЛЕНИЕ_31', 'ОТДЕЛЕНИЕ_33', 'ОТДЕЛЕНИЕ_36', 'ОТДЕЛЕНИЕ_37', 'ОТДЕЛЕНИЕ_38', 'ОТДЕЛЕНИЕ_39', 'ОТДЕЛЕНИЕ_41', 'ОТДЕЛЕНИЕ_50', 'ОТДЕЛЕНИЕ_51', 'ОТДЕЛЕНИЕ_52', 'ОТДЕЛЕНИЕ_53', 'ОТДЕЛЕНИЕ_54', 'ОТДЕЛЕНИЕ_55', 'ОТДЕЛЕНИЕ_56', 'ОТДЕЛЕНИЕ_57', 'ОТДЕЛЕНИЕ_58', 'ОТДЕЛЕНИЕ_59', 'ОТДЕЛЕНИЕ_60', 'ОТДЕЛЕНИЕ_64', 'ОТДЕЛЕНИЕ_65', 'ОТДЕЛЕНИЕ_66', 'ОТДЕЛЕНИЕ_70', 'ОТДЕЛЕНИЕ_73', 'ОТДЕЛЕНИЕ_78', 'ОТДЕЛЕНИЕ_79', 'ОТДЕЛЕНИЕ_80', 'ОТДЕЛЕНИЕ_83', 'ОТДЕЛЕНИЕ_84', 'ОТДЕЛЕНИЕ_85', 'ОТДЕЛЕНИЕ_90', 'ОТДЕЛЕНИЕ_103', 'ОТДЕЛЕНИЕ_104', 'ОТРАСЛЬ_1', 'ОТРАСЛЬ_2', 'ОТРАСЛЬ_3', 'ОТРАСЛЬ_4', 'ОТРАСЛЬ_5', 'ОТРАСЛЬ_6', 'ОТРАСЛЬ_7', 'ОТРАСЛЬ_8', 'ОТРАСЛЬ_9', 'ОТРАСЛЬ_10', 'ОТРАСЛЬ_11', 'ОТРАСЛЬ_12', 'ОТРАСЛЬ_13', 'ОТРАСЛЬ_14', 'ОТРАСЛЬ_15', 'ОТРАСЛЬ_16', 'ОТРАСЛЬ_17', 'ОТРАСЛЬ_18', 'ОТРАСЛЬ_19', 'ОТРАСЛЬ_20', 'ОТРАСЛЬ_21', 'ОТРАСЛЬ_22', 'ОТРАСЛЬ_23', 'ОТРАСЛЬ_24', 'ОТРАСЛЬ_25', 'ОТРАСЛЬ_26', 'ОТРАСЛЬ_27', 'ОТРАСЛЬ_28', 'ОТРАСЛЬ_29', 'ОТРАСЛЬ_30', 'ОТРАСЛЬ_31', 'ОТРАСЛЬ_32', 'ОТРАСЛЬ_33', 'ОТРАСЛЬ_34', 'ОТРАСЛЬ_35', 'ОТРАСЛЬ_36', 'ОТРАСЛЬ_37', 'ОТРАСЛЬ_38', 'ОТРАСЛЬ_39', 'ОТРАСЛЬ_40', 'ОТРАСЛЬ_41', 'ОТРАСЛЬ_42', 'ВОЗРАСТ', 'ПОЛ', 'ДЕТИ', 'ИЖДИВЕНЦЫ', 'ДОХОД_СЕМЬИ_', 'ДОХОД_НА_ОДНОГО_ЧЛЕНА_СЕМЬИ', 'ПЕРСОНАЛЬНЫЙ_ДОХОД', 'СУММА_ВЫДАННОГО_КРЕДИТА', 'СОБСТВЕННИК_ФАКТ.', 'ДОХОД_СУПРУГИ(А)', 'КРЕДИТЫ_ПОГАШЕНЫ', 'ПЕРВЫЙ_КРЕДИТ', 'ДЕФОЛТ60', 'train', 'ОТДЕЛЕНИЕ_107', 'ОТДЕЛЕНИЕ_108', 'ОТДЕЛЕНИЕ_110', 'ОТДЕЛЕНИЕ_114', 'ОТДЕЛЕНИЕ_115', 'ОТДЕЛЕНИЕ_116', 'ОТДЕЛЕНИЕ_117', 'ОТДЕЛЕНИЕ_119', 'ОТДЕЛЕНИЕ_120', 'ОТДЕЛЕНИЕ_121', 'ОТДЕЛЕНИЕ_122', 'ОТДЕЛЕНИЕ_125', 'ОТДЕЛЕНИЕ_126', 'ОТДЕЛЕНИЕ_127', 'ОТДЕЛЕНИЕ_135', 'ОТДЕЛЕНИЕ_136', 'ОТДЕЛЕНИЕ_137', 'ОТДЕЛЕНИЕ_138', 'ОТДЕЛЕНИЕ_140', 'ОТДЕЛЕНИЕ_143', 'ОТДЕЛЕНИЕ_144', 'ОТДЕЛЕНИЕ_145', 'ОТДЕЛЕНИЕ_146', 'ОТДЕЛЕНИЕ_148', 'ОТДЕЛЕНИЕ_149', 'ОТДЕЛЕНИЕ_153', 'ОТДЕЛЕНИЕ_154', 'ОТДЕЛЕНИЕ_155', 'ОТДЕЛЕНИЕ_156', 'ОТДЕЛЕНИЕ_157', 'ОТДЕЛЕНИЕ_159', 'ОТДЕЛЕНИЕ_160', 'ОТДЕЛЕНИЕ_161', 'ОТДЕЛЕНИЕ_162', 'ОТДЕЛЕНИЕ_163', 'ОТДЕЛЕНИЕ_164', 'ОТДЕЛЕНИЕ_165', 'ОТДЕЛЕНИЕ_166', 'ОТДЕЛЕНИЕ_167', 'ОТДЕЛЕНИЕ_168', 'ОТДЕЛЕНИЕ_169', 'ОТДЕЛЕНИЕ_170', 'ОТДЕЛЕНИЕ_171', 'ОТДЕЛЕНИЕ_177', 'ОТДЕЛЕНИЕ_178', 'ОТДЕЛЕНИЕ_179', 'ОТДЕЛЕНИЕ_181', 'ОТДЕЛЕНИЕ_182', 'ОТДЕЛЕНИЕ_184', 'ОТДЕЛЕНИЕ_185', 'ОТДЕЛЕНИЕ_186', 'ОТДЕЛЕНИЕ_187', 'ОТДЕЛЕНИЕ_188', 'ОТДЕЛЕНИЕ_189', 'ОТДЕЛЕНИЕ_190', 'ОТДЕЛЕНИЕ_191', 'ОТДЕЛЕНИЕ_192', 'ОТДЕЛЕНИЕ_193', 'ОТДЕЛЕНИЕ_194', 'ОТДЕЛЕНИЕ_195', 'ОТДЕЛЕНИЕ_196', 'ОТДЕЛЕНИЕ_199', 'ОТДЕЛЕНИЕ_200', 'ОТДЕЛЕНИЕ_201', 'ОТДЕЛЕНИЕ_202', 'ОТДЕЛЕНИЕ_203', 'ОТДЕЛЕНИЕ_204', 'ОТДЕЛЕНИЕ_205', 'ОТДЕЛЕНИЕ_206', 'ОТДЕЛЕНИЕ_208', 'ОТДЕЛЕНИЕ_210', 'ОТДЕЛЕНИЕ_211', 'ОТДЕЛЕНИЕ_212', 'ОТДЕЛЕНИЕ_213', 'ОТДЕЛЕНИЕ_214', 'ОТДЕЛЕНИЕ_216', 'ОТДЕЛЕНИЕ_217', 'ОТДЕЛЕНИЕ_218', 'ОТДЕЛЕНИЕ_219', 'ОТДЕЛЕНИЕ_220', 'ОТДЕЛЕНИЕ_223', 'ОТДЕЛЕНИЕ_224', 'ОТДЕЛЕНИЕ_225', 'ОТДЕЛЕНИЕ_226', 'ОТДЕЛЕНИЕ_227', 'ОТДЕЛЕНИЕ_228', 'ОТДЕЛЕНИЕ_229', 'ОТДЕЛЕНИЕ_230', 'ОТДЕЛЕНИЕ_231', 'ОТДЕЛЕНИЕ_232', 'ОТДЕЛЕНИЕ_240', 'ОТДЕЛЕНИЕ_241', 'ОТДЕЛЕНИЕ_243', 'ОТДЕЛЕНИЕ_245', 'ОТДЕЛЕНИЕ_246', 'ОТДЕЛЕНИЕ_247', 'ОТДЕЛЕНИЕ_248', 'ОТДЕЛЕНИЕ_249', 'ОТДЕЛЕНИЕ_264', 'РАБОТА_В_ОРГ_1', 'РАБОТА_В_ОРГ_2', 'РАБОТА_В_ОРГ_3', 'РАБОТА_ПО_НАПР_0', 'РАБОТА_ПО_НАПР_1', 'РАБОТА_ПО_НАПР_2', 'РАБОТА_ПО_НАПР_3', 'СМЕНА_МЖ_0', 'СМЕНА_МЖ_1', 'СМЕНА_МЖ_2', 'СМЕНА_МЖ_3', 'СМЕНА_МЖ_4']

In [6]:
#create square tensor from each row of data, then save it as image
data_train_train, data_train_test = train_test_split(data_train, test_size = 0.2, stratify = data_train['ДЕФОЛТ60'])
data_train_train_1 = data_train_train[data_train_train['ДЕФОЛТ60'] == 1]
data_train_train_0 = data_train_train[data_train_train['ДЕФОЛТ60'] == 0]
data_train_test_1 = data_train_test[data_train_test['ДЕФОЛТ60'] == 1]
data_train_test_0 = data_train_test[data_train_test['ДЕФОЛТ60'] == 0]

counter = 1
for row in data_train_train_1.drop(columns = ['ДЕФОЛТ60', 'train']).to_numpy():
    img = torch.from_numpy(row.reshape(16, 16))
    save_image(img, f'img/train/1/img{counter}.png')
    counter += 1
counter = 1
for row in data_train_train_0.drop(columns = ['ДЕФОЛТ60', 'train']).to_numpy():
    img = torch.from_numpy(row.reshape(16, 16))
    save_image(img, f'img/train/0/img{counter}.png')
    counter += 1
counter = 1
for row in data_train_test_1.drop(columns = ['ДЕФОЛТ60', 'train']).to_numpy():
    img = torch.from_numpy(row.reshape(16, 16))
    save_image(img, f'img/test/1/img{counter}.png')
    counter += 1
counter = 1
for row in data_train_test_0.drop(columns = ['ДЕФОЛТ60', 'train']).to_numpy():
    img = torch.from_numpy(row.reshape(16, 16))
    save_image(img, f'img/test/0/img{counter}.png')
    counter += 1
counter = 1
for row in data_test.drop(columns = ['ДЕФОЛТ60', 'train']).to_numpy():
    img = torch.from_numpy(row.reshape(16, 16))
    save_image(img, f'img/score/img{counter}.png')
    counter += 1

In [ ]:
columns_order = ['ВОЗРАСТ', 'ПОЛ', 'ДЕТИ', 'ИЖДИВЕНЦЫ', 'ДОХОД_СЕМЬИ_', 'ДОХОД_НА_ОДНОГО_ЧЛЕНА_СЕМЬИ',\
                 'ПЕРСОНАЛЬНЫЙ_ДОХОД', 'СУММА_ВЫДАННОГО_КРЕДИТА', 'СОБСТВЕННИК_ФАКТ.', 'ДОХОД_СУПРУГИ(А)',\
                 'КРЕДИТЫ_ПОГАШЕНЫ', 'ПЕРВЫЙ_КРЕДИТ', 'ДЕФОЛТ60', 'train', 'АВТО_0', 'АВТО_1', 'АВТО_2',\
                 'АВТО_3', 'БРАК_1', 'БРАК_2', 'БРАК_3', 'БРАК_4', 'ГОРОД_1', 'ГОРОД_2', 'ГОРОД_3', 'ГОРОД_5',\
                 'ГОРОД_6', 'ГОРОД_8', 'ГОРОД_9', 'ГОРОД_10', 'ГОРОД_12', 'ГОРОД_13', 'ГОРОД_15', 'ГОРОД_16',\
                 'ГОРОД_19', 'ГОРОД_20', 'ГОРОД_22', 'ГОРОД_27', 'ГОРОД_29', 'ГОРОД_30', 'ГОРОД_31', 'ГОРОД_32',\
                 'ГОРОД_33', 'ГОРОД_35', 'ДОЛЖНОСТЬ_1', 'ДОЛЖНОСТЬ_3', 'ДОЛЖНОСТЬ_4', 'ДОЛЖНОСТЬ_5',\
                 'ДОЛЖНОСТЬ_6', 'ИНОСТР.ЯЗЫК_0', 'ИНОСТР.ЯЗЫК_1', 'ИНОСТР.ЯЗЫК_2', 'ИНОСТР.ЯЗЫК_3',\
                 'ИНОСТР.ЯЗЫК_4', 'ОБРАЗОВАНИЕ_1', 'ОБРАЗОВАНИЕ_2', 'ОБРАЗОВАНИЕ_3', 'ОБРАЗОВАНИЕ_4',\
                 'ОТДЕЛЕНИЕ_3', 'ОТДЕЛЕНИЕ_7', 'ОТДЕЛЕНИЕ_8', 'ОТДЕЛЕНИЕ_10', 'ОТДЕЛЕНИЕ_11', 'ОТДЕЛЕНИЕ_14',\
                 'ОТДЕЛЕНИЕ_16', 'ОТДЕЛЕНИЕ_17', 'ОТДЕЛЕНИЕ_18', 'ОТДЕЛЕНИЕ_24', 'ОТДЕЛЕНИЕ_25', 'ОТДЕЛЕНИЕ_27',\
                 'ОТДЕЛЕНИЕ_28', 'ОТДЕЛЕНИЕ_29', 'ОТДЕЛЕНИЕ_30', 'ОТДЕЛЕНИЕ_31', 'ОТДЕЛЕНИЕ_33', 'ОТДЕЛЕНИЕ_36',\
                 'ОТДЕЛЕНИЕ_37', 'ОТДЕЛЕНИЕ_38', 'ОТДЕЛЕНИЕ_39', 'ОТДЕЛЕНИЕ_41', 'ОТДЕЛЕНИЕ_50', 'ОТДЕЛЕНИЕ_51',\
                 'ОТДЕЛЕНИЕ_52', 'ОТДЕЛЕНИЕ_53', 'ОТДЕЛЕНИЕ_54', 'ОТДЕЛЕНИЕ_55', 'ОТДЕЛЕНИЕ_56', 'ОТДЕЛЕНИЕ_57',\
                 'ОТДЕЛЕНИЕ_58', 'ОТДЕЛЕНИЕ_59', 'ОТДЕЛЕНИЕ_60', 'ОТДЕЛЕНИЕ_64', 'ОТДЕЛЕНИЕ_65', 'ОТДЕЛЕНИЕ_66',\
                 'ОТДЕЛЕНИЕ_70', 'ОТДЕЛЕНИЕ_73', 'ОТДЕЛЕНИЕ_78', 'ОТДЕЛЕНИЕ_79', 'ОТДЕЛЕНИЕ_80', 'ОТДЕЛЕНИЕ_83',\
                 'ОТДЕЛЕНИЕ_84', 'ОТДЕЛЕНИЕ_85', 'ОТДЕЛЕНИЕ_90', 'ОТДЕЛЕНИЕ_103', 'ОТДЕЛЕНИЕ_104',\
                 'ОТДЕЛЕНИЕ_107', 'ОТДЕЛЕНИЕ_108', 'ОТДЕЛЕНИЕ_110', 'ОТДЕЛЕНИЕ_114', 'ОТДЕЛЕНИЕ_115',\
                 'ОТДЕЛЕНИЕ_116', 'ОТДЕЛЕНИЕ_117', 'ОТДЕЛЕНИЕ_119', 'ОТДЕЛЕНИЕ_120', 'ОТДЕЛЕНИЕ_121',\
                 'ОТДЕЛЕНИЕ_122', 'ОТДЕЛЕНИЕ_125', 'ОТДЕЛЕНИЕ_126', 'ОТДЕЛЕНИЕ_127', 'ОТДЕЛЕНИЕ_135',\
                 'ОТДЕЛЕНИЕ_136', 'ОТДЕЛЕНИЕ_137', 'ОТДЕЛЕНИЕ_138', 'ОТДЕЛЕНИЕ_140', 'ОТДЕЛЕНИЕ_143',\
                 'ОТДЕЛЕНИЕ_144', 'ОТДЕЛЕНИЕ_145', 'ОТДЕЛЕНИЕ_146', 'ОТДЕЛЕНИЕ_148', 'ОТДЕЛЕНИЕ_149',\
                 'ОТДЕЛЕНИЕ_153', 'ОТДЕЛЕНИЕ_154', 'ОТДЕЛЕНИЕ_155', 'ОТДЕЛЕНИЕ_156', 'ОТДЕЛЕНИЕ_157',\
                 'ОТДЕЛЕНИЕ_159', 'ОТДЕЛЕНИЕ_160', 'ОТДЕЛЕНИЕ_161', 'ОТДЕЛЕНИЕ_162', 'ОТДЕЛЕНИЕ_163',\
                 'ОТДЕЛЕНИЕ_164', 'ОТДЕЛЕНИЕ_165', 'ОТДЕЛЕНИЕ_166', 'ОТДЕЛЕНИЕ_167', 'ОТДЕЛЕНИЕ_168',\
                 'ОТДЕЛЕНИЕ_169', 'ОТДЕЛЕНИЕ_170', 'ОТДЕЛЕНИЕ_171', 'ОТДЕЛЕНИЕ_177', 'ОТДЕЛЕНИЕ_178',\
                 'ОТДЕЛЕНИЕ_179', 'ОТДЕЛЕНИЕ_181', 'ОТДЕЛЕНИЕ_182', 'ОТДЕЛЕНИЕ_184', 'ОТДЕЛЕНИЕ_185',\
                 'ОТДЕЛЕНИЕ_186', 'ОТДЕЛЕНИЕ_187', 'ОТДЕЛЕНИЕ_188', 'ОТДЕЛЕНИЕ_189', 'ОТДЕЛЕНИЕ_190',\
                 'ОТДЕЛЕНИЕ_191', 'ОТДЕЛЕНИЕ_192', 'ОТДЕЛЕНИЕ_193', 'ОТДЕЛЕНИЕ_194', 'ОТДЕЛЕНИЕ_195',\
                 'ОТДЕЛЕНИЕ_196', 'ОТДЕЛЕНИЕ_199', 'ОТДЕЛЕНИЕ_200', 'ОТДЕЛЕНИЕ_201', 'ОТДЕЛЕНИЕ_202',\
                 'ОТДЕЛЕНИЕ_203', 'ОТДЕЛЕНИЕ_204', 'ОТДЕЛЕНИЕ_205', 'ОТДЕЛЕНИЕ_206', 'ОТДЕЛЕНИЕ_208',\
                 'ОТДЕЛЕНИЕ_210', 'ОТДЕЛЕНИЕ_211', 'ОТДЕЛЕНИЕ_212', 'ОТДЕЛЕНИЕ_213', 'ОТДЕЛЕНИЕ_214',\
                 'ОТДЕЛЕНИЕ_216', 'ОТДЕЛЕНИЕ_217', 'ОТДЕЛЕНИЕ_218', 'ОТДЕЛЕНИЕ_219', 'ОТДЕЛЕНИЕ_220',\
                 'ОТДЕЛЕНИЕ_223', 'ОТДЕЛЕНИЕ_224', 'ОТДЕЛЕНИЕ_225', 'ОТДЕЛЕНИЕ_226', 'ОТДЕЛЕНИЕ_227',\
                 'ОТДЕЛЕНИЕ_228', 'ОТДЕЛЕНИЕ_229', 'ОТДЕЛЕНИЕ_230', 'ОТДЕЛЕНИЕ_231', 'ОТДЕЛЕНИЕ_232',\
                 'ОТДЕЛЕНИЕ_240', 'ОТДЕЛЕНИЕ_241', 'ОТДЕЛЕНИЕ_243', 'ОТДЕЛЕНИЕ_245', 'ОТДЕЛЕНИЕ_246',\
                 'ОТДЕЛЕНИЕ_247', 'ОТДЕЛЕНИЕ_248', 'ОТДЕЛЕНИЕ_249', 'ОТДЕЛЕНИЕ_264', 'ОТРАСЛЬ_1', 'ОТРАСЛЬ_2',\
                 'ОТРАСЛЬ_3', 'ОТРАСЛЬ_4', 'ОТРАСЛЬ_5', 'ОТРАСЛЬ_6', 'ОТРАСЛЬ_7', 'ОТРАСЛЬ_8', 'ОТРАСЛЬ_9',\
                 'ОТРАСЛЬ_10', 'ОТРАСЛЬ_11', 'ОТРАСЛЬ_12', 'ОТРАСЛЬ_13', 'ОТРАСЛЬ_14', 'ОТРАСЛЬ_15',\
                 'ОТРАСЛЬ_16', 'ОТРАСЛЬ_17', 'ОТРАСЛЬ_18', 'ОТРАСЛЬ_19', 'ОТРАСЛЬ_20', 'ОТРАСЛЬ_21',\
                 'ОТРАСЛЬ_22', 'ОТРАСЛЬ_23', 'ОТРАСЛЬ_24', 'ОТРАСЛЬ_25', 'ОТРАСЛЬ_26', 'ОТРАСЛЬ_27',\
                 'ОТРАСЛЬ_28', 'ОТРАСЛЬ_29', 'ОТРАСЛЬ_30', 'ОТРАСЛЬ_31', 'ОТРАСЛЬ_32', 'ОТРАСЛЬ_33',\
                 'ОТРАСЛЬ_34', 'ОТРАСЛЬ_35', 'ОТРАСЛЬ_36', 'ОТРАСЛЬ_37', 'ОТРАСЛЬ_38', 'ОТРАСЛЬ_39',\
                 'ОТРАСЛЬ_40', 'ОТРАСЛЬ_41', 'ОТРАСЛЬ_42', 'РАБОТА_В_ОРГ_1', 'РАБОТА_В_ОРГ_2', 'РАБОТА_В_ОРГ_3',\
                 'РАБОТА_ПО_НАПР_0', 'РАБОТА_ПО_НАПР_1', 'РАБОТА_ПО_НАПР_2', 'РАБОТА_ПО_НАПР_3', 'СМЕНА_МЖ_0',\
                 'СМЕНА_МЖ_1', 'СМЕНА_МЖ_2', 'СМЕНА_МЖ_3', 'СМЕНА_МЖ_4']